server:
  port: 10010
spring:
  application:
    name: blogs-gateway
zuul:
  prefix: /api # 添加路由前缀
  retryable: true
  routes:
    blogs-admin: /**
#    blogs-upload:
#      path: /upload/**
#      serviceId: blogs-upload
#      strip-prefix: false
#    blogs-admin:
#      path: /admin/**
#      serviceId: blogs-admin
#      strip-prefix: false
#    blogs-auth:
#      path: /auth/**
#      serviceId: blogs-auth
#      strip-prefix: false
#    blogs-message:
#      path: /message/**
#      serviceId: blogs-message
#      strip-prefix: false
#    blogs-websocket:
#      path: /chat/**
#      serviceId: blogs-websocket
#      strip-prefix: false


#取消敏感词汇  "Cookie", "Set-Cookie", "Authorization"
  sensitive-headers:
  add-host-header: true #添加头信息

ribbon:
  ConnectTimeout: 250 # 连接超时时间(ms)
  ReadTimeout: 2000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 1 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 10000 # 熔断超时时长：10000ms
myblogs:
  jwt:
    pubKeyPath: /opt/myblog/jar-pro/file/keys/rsa.pub # 公钥地址
    cookieName: MY_BLOG
  filter:
    allowPaths:
      - /api/upload
      - /api/message
      - /api/admin
    notAllowPaths:
      - /api/admin/project/save
#      - /api/message/send
#      - /api/message/baidu/save

#      - /api/user/check
#logging:
#  level: warn
