server:
  port: 8021


spring:
  application:
    name: blogs-admin
  #  # 环境设置：dev、test、prod
  profiles:
    active: dev
  datasource:
    password: ${jdbc.password}
    username: ${jdbc.username}
    url: ${jdbc.url}
    #    &serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      # 连接超时时间:毫秒，小于250毫秒，否则被重置为默认值30秒
      connection-timeout: 6000000
      # 最大连接数，小于等于0会被重置为默认值10；大于零小于1会被重置为minimum-idle的值
      maximum-pool-size: 20
      # 最小空闲连接，默认值10，小于0或大于maximum-pool-size，都会重置为maximum-pool-size
      minimum-idle: 5
      # 空闲连接超时时间，默认值600000（10分钟），大于等于max-lifetime且max-lifetime>0，会被重置为0；不等于0且小于10秒，会被重置为10秒。
      # 只有空闲连接数大于最大连接数且空闲时间超过该值，才会被释放
      idle-timeout: 50000000
      # 连接最大存活时间.不等于0且小于30秒，会被重置为默认值30分钟.设置应该比mysql设置的超时时间短
      max-lifetime: 55000000
      #      # 连接池名称，默认HikariPool-1
      pool-name: GuliHikariPool
  #      connection-test-query: select 1
  #  spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
  #  spring.jackson.time-zone=GMT+8
#  jackson:  千万别设置 真鸡巴坑
#    time-zone: GMT+8
#    #    joda-date-time-format: yyyy-MM-dd HH:mm:ss
#    date-format: yyyy-MM-dd HH:mm:ss



mybatis-plus:
  mapper-locations: classpath:/mappers/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.blog.pojo
  #typeEnumsPackage: com.tyut.pojo.enums
  global-config:
    #刷新mapper 调试神器
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
#      id-type: AUTO
#      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
#      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
#      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
#      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      db-type: mysql
    refresh: true
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.xxx
    #自定义SQL注入器
  #sql-injector: com.baomidou.mybatisplus.extension.injector.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

blogs:
  jwt:
    secret: ${jwt.secret} # 登录校验的密钥
    pubKeyPath: ${jwt.pubKeyPath} # 公钥地址
    priKeyPath: ${jwt.priKeyPath} # 私钥地址
    expire: ${jwt.expire} # 过期时间,单位分钟
  cookie:
    loginName: ${cookie.loginName}
    maxAge: 604800
#logging:
#  level: warn